name: Build and Test Spring Boot Kotlin App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java 17 (or the version your app is using)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      # Cache Gradle dependencies to speed up builds
      - name: Cache Gradle dependencies
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # Set up Gradle wrapper
      - name: Set up Gradle wrapper
        run: ./gradlew wrapper

      # Build the project using Gradle
      - name: Build with Gradle
        run: ./gradlew build

      # Run tests
      - name: Run tests
        run: ./gradlew test

      # Optional: Package the application
      - name: Build JAR
        run: ./gradlew bootJar

      # Optional: Upload the artifact (if you need to store the JAR file)
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v3
        with:
          name: spring-boot-kotlin-app
          path: build/libs/*.jar
